# Generated by Django 4.2.8 on 2024-10-04 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'furniture_categories',
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture', to='furniture.category')),
            ],
            options={
                'verbose_name': 'Furniture',
                'verbose_name_plural': 'Furniture',
                'db_table': 'furniture_items',
            },
        ),
        migrations.CreateModel(
            name='FurnitureVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('variant_name', models.CharField(max_length=100)),
                ('variant_value', models.CharField(max_length=100)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='furniture.furniture')),
            ],
            options={
                'verbose_name': 'Furniture Variant',
                'verbose_name_plural': 'Furniture Variants',
                'db_table': 'furniture_variants',
            },
        ),
        migrations.CreateModel(
            name='FurnitureAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=255)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='furniture.furniture')),
            ],
            options={
                'verbose_name': 'Furniture Attribute',
                'verbose_name_plural': 'Furniture Attributes',
                'db_table': 'furniture_attributes',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('discount_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='furniture.furniture')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'furniture_discounts',
            },
        ),
    ]
