# Generated by Django 4.2.8 on 2024-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
